### ISSUE TITLE
[BUG] 如果在 WS Server 啟動後才創立的房間，貌似會無法正確讀取 memberList

### ISSUE THREAD

**Issue by MeteorVE** [a6976933/SE5-Backend-Websocket#1]
## Context

如果在 WS Server 啟動後才創立的房間，貌似會無法正確讀取 memberList

## Process

0. 環境啟動
1. 登入兩個帳號
2. A 帳號新建房間
3. B 帳號加入
4. A 帳號可以發訊息，但是 B 不能

## Expected result

可以發訊息

## Current result

B 帳號不能發訊息

## Possible Fix

不確定是不是需要等 update 的 signal 出現，會同時讓 WS 除了 notfiy 前端 也會去 query 

## Screenshot

房間號碼 26
A帳號 = 房主 ID 25
B 帳號 = 新人 ID 21

![image](https://user-images.githubusercontent.com/15828515/121095379-d4d36880-c822-11eb-9ca5-4c226b89dccd.png)

## Examples

none

**Comment by a6976933** [comment]
沒Bug了
